
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * This class extends AbstractTab. It is a tab for viewing the information about clients
 * It is aimed to be added to the tabbedPane of the main window
 */

/**
 *
 * @author brendan
 */
public class ClientTab extends AbstractTab {

//Constructor 
    
    //first use the AbstractTab constructor to build the mainWin and selectedRow fields. Then create the components
    public ClientTab(Main_W mainWin) throws SQLException {
        super(mainWin);
       
        //creation of the table
        clientTable = new JTable(buildTableModel(getContentsOfTable())); // Displays the table
        
        //Add sorter on the table
        clientTable.setAutoCreateRowSorter(true);
        
        //clientTable.setPreferredScrollableViewportSize(new Dimension(500, 70));
        //clientTable.setFillsViewportHeight(true);
        
        //we only want a single selection for this table
        clientTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);      
        
        //add listener on row selection
        ListSelectionModel rowSM = clientTable.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                tableValueChangedEvent(e);  
            }
        });
         
        initComponents();
        paneForTable.setViewportView(clientTable);
          
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addClient = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        paneForTable = new javax.swing.JScrollPane();
        modifButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        addClient.setText("Add");
        addClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientActionPerformed(evt);
            }
        });

        modifButton.setText("Modify");
        modifButton.setEnabled(false);
        modifButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.setEnabled(false);
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paneForTable)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(addClient)
                        .addGap(18, 18, 18)
                        .addComponent(modifButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeButton)
                        .addGap(0, 175, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClient)
                    .addComponent(modifButton)
                    .addComponent(removeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneForTable, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
//Private methods
    
    //fonction called when selecting a row in the table
    //We enable the modif and remove buttons, and update selectedRo to the id of the client selected
    private void tableValueChangedEvent(ListSelectionEvent e) {
        ListSelectionModel lsm = (ListSelectionModel)e.getSource();
        if (lsm.isSelectionEmpty()) {
            modifButton.setEnabled(false);
            removeButton.setEnabled(false);
        } else {
            
            //if a line is selected, selectedRow take the client id 
            //and we enable the modif and remove buttons
            
            int viewRow = clientTable.getSelectedRow();
            
            Statement stmt=null;
            String name=(String)clientTable.getValueAt(viewRow,0);
            try{
                Connection conn=mainWin.getConnection();
                stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT cl_id FROM V_Clients WHERE name ='"+name+"'");
                //SelectedRow taes the id of the selected client
                if (rs.next()) { selectedRow=rs.getInt("cl_id"); }
                else { //here the selection went wrong
                    JOptionPane.showMessageDialog(this, "Something went wrong! request problem",
                    "Warning", JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (SQLException se) {
                //Handle errors for JDBC
                JOptionPane.showMessageDialog(this, "Unexpected error, request problem\nDetails : "+se.getMessage(),
                    "Warning", JOptionPane.ERROR_MESSAGE);
            } finally {
                //finally block used to close resources
                try{
                    if(stmt!=null)
                    stmt.close();
                }catch(SQLException se2){ }// nothing we can do
            }//end finally
                
            modifButton.setEnabled(true);
            removeButton.setEnabled(true);
        }
    }
    
    //When clicking the add button, we build and show a AddClient2 dialog
    private void addClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientActionPerformed
        AddClient2 NewClientW = new AddClient2(mainWin,this,true);       
        NewClientW.setLocationRelativeTo(null);
        NewClientW.setVisible(true);
    }//GEN-LAST:event_addClientActionPerformed
    
    //When clicking the modif button, we first put all the needed information in an hashmap, 
    //then we build and show a ModifyClient dialog
    private void modifButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifButtonActionPerformed
        HashMap<Integer, String> content = new HashMap<>();
        Statement stmt = null;
        try{
            Connection conn=mainWin.getConnection();
            stmt = conn.createStatement();
            String sqlQuery;
            sqlQuery = "SELECT V_Clients.name,V_Clients.phone1,V_Clients.phone2,V_Clients.adress,V_Clients.delivery_adress,V_Clients.email,V_Clients.qq,V_Clients.infos,"
                    + "main.street,main.city,main.country,main.zip_code,"
                    + "dev.street,dev.city,dev.country,dev.zip_code "
                    + "from V_Clients inner join V_Adresses as main on V_Clients.adress=main.ad_id "
                    +  "inner join V_Adresses as dev on V_Clients.delivery_adress=dev.ad_id "
                    + "where cl_id="+Integer.toString(selectedRow);
            ResultSet rs = stmt.executeQuery(sqlQuery);
            if (rs.next()) {
                content.put(1,rs.getString("V_Clients.name"));
                content.put(2,rs.getString("V_Clients.phone1"));
                content.put(3,rs.getString("V_Clients.phone2"));
                content.put(4,rs.getString("V_Clients.email"));
                content.put(5,rs.getString("V_Clients.qq"));
                content.put(6,rs.getString("V_Clients.infos"));
                content.put(7,rs.getString("main.street"));
                content.put(8,rs.getString("main.city"));
                content.put(9,rs.getString("main.country"));
                content.put(10,rs.getString("main.zip_code"));
                content.put(11,rs.getString("dev.street"));
                content.put(12,rs.getString("dev.city"));
                content.put(13,rs.getString("dev.country"));
                content.put(14,rs.getString("dev.zip_code"));
                
                //if delivery adress is also the main adress, we add a content Y
                if (rs.getInt("adress")==rs.getInt("delivery_adress")) {
                    content.put(15, "Y");
                } else {
                    content.put(15, "N");
                }
            }
        }catch(SQLException se) {
                //Handle errors for JDBC
                JOptionPane.showMessageDialog(this, "Unexpected error, request problem\nDetails : "+se.getMessage(),
                    "Warning", JOptionPane.ERROR_MESSAGE);
        } finally {
            //finally block used to close resources
            try{
                if(stmt!=null)
                stmt.close();
            }catch(SQLException se2){ }// nothing we can do
        }//end finally
        
        ModifyClient ModClientW = new ModifyClient(mainWin,this,true,content,selectedRow);       
        ModClientW.setLocationRelativeTo(null);
        ModClientW.setVisible(true);

    }//GEN-LAST:event_modifButtonActionPerformed

    //When clicking the remove button, we look for the needed id, and then make the delete request
    //and finally update the table content
    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        //we get the client name, adress and delivery adress
        String name="",adress="",deli_adress="";
        Statement stmt = null;
        try{
            Connection conn=mainWin.getConnection();
            stmt = conn.createStatement();
            String sqlQuery;           
            sqlQuery="SELECT name,adress,delivery_adress FROM V_Clients WHERE cl_id="+Integer.toString(selectedRow);
            ResultSet rs = stmt.executeQuery(sqlQuery);
            if (rs.next()) {
                name = rs.getString("name");
                adress = rs.getString("adress");
                deli_adress = rs.getString("delivery_adress");
            } else { //here the selection went wrong
                    JOptionPane.showMessageDialog(this, "Something went wrong! request problem",
                    "Warning", JOptionPane.ERROR_MESSAGE);
            }
        } catch(SQLException se) {
                //Handle errors for JDBC
                JOptionPane.showMessageDialog(this, "Unexpected error, select request problem\nDetails : "+se.getMessage(),
                    "Warning", JOptionPane.ERROR_MESSAGE);
        } finally {
            //finally block used to close resources
        try{
            if(stmt!=null)
                stmt.close();
        }catch(SQLException se2){ }// nothing we can do
        }//end finally

        
        //little dialog before making the delete requests
        Object[] options = {"Yes","No"};    
        int n = JOptionPane.showOptionDialog(this,"Are you sure you want to remove this client : "+name+" ?","Removing client",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
        if (n==JOptionPane.YES_OPTION) {
            // here we are sure we want to remove the client
            stmt = null;
            try{
                Connection conn=mainWin.getConnection();
                stmt = conn.createStatement();
                String sqlQuery;
                sqlQuery="DELETE FROM V_Clients WHERE cl_id="+Integer.toString(selectedRow);
                stmt.executeUpdate(sqlQuery);
                sqlQuery="DELETE FROM V_Adresses WHERE ad_id="+adress;
                stmt.executeUpdate(sqlQuery);
                sqlQuery="DELETE FROM V_Adresses WHERE ad_id="+deli_adress;
                stmt.executeUpdate(sqlQuery);
            } catch(SQLException se) {
                //Handle errors for JDBC
                JOptionPane.showMessageDialog(this, "Unexpected error, delete request problem\nDetails : "+se.getMessage(),
                    "Warning", JOptionPane.ERROR_MESSAGE);
            } finally {
            //finally block used to close resources
            try{
                if(stmt!=null) stmt.close();
            } catch(SQLException se2){ }// nothing we can do
            }//end finally
            
            //and we update the table
            try {
                updateClientTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Unexpected error, problem creating table\nDetails : "+ex.getMessage(),
                    "Warning", JOptionPane.ERROR_MESSAGE);
            }
            
        }
   
    }//GEN-LAST:event_removeButtonActionPerformed

    //Function used to get the contents we want to display in the table
    private ResultSet getContentsOfTable() throws SQLException {
        ResultSet rs = null;
        try{
            Connection conn=mainWin.getConnection();
            Statement stmt = conn.createStatement();
            rs = stmt.executeQuery("select V_Clients.name, V_Clients.phone1, V_Clients.phone2, V_Clients.email, V_Clients.qq, "
              + "V_Adresses.street, V_Adresses.city, V_Adresses.zip_code, V_Adresses.country, V_Clients.infos from V_Clients"
              + " inner join V_Adresses on V_Clients.adress=V_Adresses.ad_id");
        } catch(SQLException se) {
                //Handle errors for JDBC
                JOptionPane.showMessageDialog(this, "Unexpected error, select request problem\nDetails : "+se.getMessage(),
                    "Warning", JOptionPane.ERROR_MESSAGE);
        } 
        return rs;
    }
    

//Public methods

    //update the content of the table
    public void updateClientTable() throws SQLException {
        clientTable.setModel(buildTableModel(getContentsOfTable()));
    }
    
    
//Components of the tab
    
    private JTable clientTable;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClient;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton modifButton;
    private javax.swing.JScrollPane paneForTable;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables




}
