
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author brendan
 */
public class ManageCat extends javax.swing.JDialog {

    /**
     * Creates new form ManageCat
     */
    public ManageCat(java.awt.Frame parent, boolean modal, ProductTab product) {
        super(parent, modal);
        this.product=product;
        this.treeString=product.getLevel();
        initComponents();
        
        initializeList1();
        
        jList2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        jList1.addListSelectionListener( new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting() == false) {

                    if (jList1.getSelectedIndex() == -1) {
                    //No selection, disable fire button.
                    addChildButton.setEnabled(false);
                    parentUp.setEnabled(false);
                    parentDown.setEnabled(false);
                    modifyParent.setEnabled(false);
                    removeParent.setEnabled(false);

                    } else {
                    //Selection, enable the fire button.
                    addChildButton.setEnabled(true);   
                    modifyParent.setEnabled(true);
                    removeParent.setEnabled(true);
                    if (jList1.getSelectedIndex()==0) { 
                        parentUp.setEnabled(false); 
                    } else {
                        parentUp.setEnabled(true);
                    }
                    if (jList1.getSelectedIndex()==treeString.size()-1) { 
                        parentDown.setEnabled(false); 
                    } else {
                        parentDown.setEnabled(true);
                    }
                    //fill the jList2 with the item corresponding to the level 1 selection
                    initializeList2(jList1.getSelectedIndex());
                    }
                }
            }

        });
        
        jList2.addListSelectionListener( new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting() == false) {
                    int index1 = jList1.getSelectedIndex();
                    int index2 = jList2.getSelectedIndex();
                    if (index2 == -1) {
                    //No selection, disable fire button.
                    childUp.setEnabled(false);
                    childDown.setEnabled(false);
                    modifyChild.setEnabled(false);
                    removeChild.setEnabled(false);

                    } else {
                        //Selection, enable the fire button.
                        modifyChild.setEnabled(true);
                        removeChild.setEnabled(true);
                        //je sais pas pourquoi il commence a 1 ici
                        if (index2==1) { 
                            childUp.setEnabled(false); 
                        } else {
                            childUp.setEnabled(true);
                        }
                        if (index2==treeString.get(index1).length-1) { 
                            childDown.setEnabled(false); 
                        } else {
                            childDown.setEnabled(true);
                        }   
                    
                    }
                }
            }

        });
        
        
    }
    
    
    private void initializeList1() {
        String[] level1=new String[treeString.size()];
        for (int i=0; i<level1.length; i++) {
            level1[i]=treeString.get(i)[0];
        }
        jList1.setListData(level1);
    }
    
    private void initializeList2(int index) {
        String[] level2=new String[treeString.get(index).length];
        System.arraycopy(treeString.get(index), 1, level2, 1, level2.length - 1);
        jList2.setListData(level2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        addParentButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        addChildButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        finishButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        parentUp = new javax.swing.JButton();
        parentDown = new javax.swing.JButton();
        modifyParent = new javax.swing.JButton();
        modifyChild = new javax.swing.JButton();
        childUp = new javax.swing.JButton();
        childDown = new javax.swing.JButton();
        removeParent = new javax.swing.JButton();
        removeChild = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Product categories");

        jLabel2.setText("Parent");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        addParentButton.setText("Add parent");
        addParentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addParentButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Child");

        jScrollPane2.setViewportView(jList2);

        addChildButton.setText("Add child");
        addChildButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChildButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        parentUp.setText("up");
        parentUp.setEnabled(false);
        parentUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentUpActionPerformed(evt);
            }
        });

        parentDown.setText("down");
        parentDown.setEnabled(false);
        parentDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentDownActionPerformed(evt);
            }
        });

        modifyParent.setText("Modify");
        modifyParent.setEnabled(false);
        modifyParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyParentActionPerformed(evt);
            }
        });

        modifyChild.setText("Modify");
        modifyChild.setEnabled(false);
        modifyChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyChildActionPerformed(evt);
            }
        });

        childUp.setText("Up");
        childUp.setEnabled(false);
        childUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childUpActionPerformed(evt);
            }
        });

        childDown.setText("Down");
        childDown.setEnabled(false);
        childDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childDownActionPerformed(evt);
            }
        });

        removeParent.setText("Remove");
        removeParent.setEnabled(false);
        removeParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeParentActionPerformed(evt);
            }
        });

        removeChild.setText("Remove");
        removeChild.setEnabled(false);
        removeChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeChildActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addParentButton)
                                    .addComponent(modifyParent)
                                    .addComponent(parentDown)
                                    .addComponent(parentUp)
                                    .addComponent(removeParent))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addChildButton)
                                    .addComponent(modifyChild)
                                    .addComponent(childUp)
                                    .addComponent(childDown)
                                    .addComponent(removeChild))))
                        .addGap(78, 78, 78))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(18, 18, 18)
                .addComponent(finishButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addParentButton)
                                .addGap(18, 18, 18)
                                .addComponent(modifyParent))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addChildButton)
                                .addGap(18, 18, 18)
                                .addComponent(modifyChild)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parentUp)
                            .addComponent(childUp, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parentDown)
                            .addComponent(childDown))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeParent)
                            .addComponent(removeChild))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addParentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addParentButtonActionPerformed
        // add a parent in the list, create a default 'other' child 
        String answerCat = JOptionPane.showInputDialog (this, "New category :") ;
        if (answerCat.length() > 80) {
            JOptionPane.showMessageDialog(this, "Category too long, please make it shorter",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (answerCat.length() > 0) {
            String[] newLevel1 = {answerCat,"Other"};
            treeString.add(newLevel1);
            initializeList1();
        }
        
    }//GEN-LAST:event_addParentButtonActionPerformed

    private void addChildButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChildButtonActionPerformed
        //add a child
        String answerCat = JOptionPane.showInputDialog (this, "New subcategory :") ;
        if (answerCat.length() > 80) {
            JOptionPane.showMessageDialog(this, "Category too long, please make it shorter",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (answerCat.length() > 0) {
            int index = jList1.getSelectedIndex();
            String[] subCat = new String[treeString.get(index).length+1];   //we copy what we already have
            System.arraycopy(treeString.get(index), 0, subCat, 0, subCat.length-1);
            subCat[subCat.length-1]=answerCat;  //and add the new one at the end
            treeString.set(index,subCat);
            initializeList2(index);
        }
    }//GEN-LAST:event_addChildButtonActionPerformed

    private void parentUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentUpActionPerformed
        // moving upstairs
        int index = jList1.getSelectedIndex();
        //if we are on the top of the list we do nothing
        if (index==0) {return;}
        //else we store the line upstrairs
        String[] copy=treeString.get(index-1).clone();
        treeString.set(index-1,treeString.get(index));
        treeString.set(index,copy);
        //refresh the list
        initializeList1();
        jList1.setSelectedIndex(index-1);
        
        
    }//GEN-LAST:event_parentUpActionPerformed

    private void parentDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentDownActionPerformed
        // TODO add your handling code here:
         int index = jList1.getSelectedIndex();
        //if we are on the top of the list we do nothing
        if (index==treeString.size()) {return;}
        //else we store the line upstrairs
        String[] copy=treeString.get(index+1).clone();
        treeString.set(index+1,treeString.get(index));
        treeString.set(index,copy);
        //refresh the list
        initializeList1();
        jList1.setSelectedIndex(index+1);
    }//GEN-LAST:event_parentDownActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // close the window
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void modifyParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyParentActionPerformed
        // modify a parent
        String modCat = JOptionPane.showInputDialog (this, "New category :",jList1.getSelectedValue()) ;
        if (modCat.length() > 80) {
            JOptionPane.showMessageDialog(this, "Category too long, please make it shorter",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (modCat.length() > 0) {
            int index = jList1.getSelectedIndex();
            String[] subCat = new String[treeString.get(index).length];   //we copy what we already have
            System.arraycopy(treeString.get(index), 0, subCat, 0, subCat.length);
            subCat[0]=modCat;  //and add the new one at the end
            treeString.set(index,subCat);
            initializeList1();
            jList1.setSelectedIndex(index);
        }
    }//GEN-LAST:event_modifyParentActionPerformed

    private void modifyChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyChildActionPerformed
        // modify a child
        String modCat = JOptionPane.showInputDialog (this, "New subcategory :",jList2.getSelectedValue()) ;
        if (modCat.length() > 80) {
            JOptionPane.showMessageDialog(this, "Category too long, please make it shorter",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (modCat.length() > 0) {
            int index1 = jList1.getSelectedIndex();
            int index2=jList2.getSelectedIndex();
            String[] subCat = new String[treeString.get(index1).length];   //we copy what we already have
            System.arraycopy(treeString.get(index1), 0, subCat, 0, subCat.length);
            subCat[index2]=modCat;  //and add the new one 
            treeString.set(index1,subCat);
            initializeList2(index1);
            jList2.setSelectedIndex(index2);
        }
    }//GEN-LAST:event_modifyChildActionPerformed

    private void childUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childUpActionPerformed
        // moving upstairs
        int index1 = jList1.getSelectedIndex();
        int index2 = jList2.getSelectedIndex();
        //if we are on the top of the list we do nothing
        if (index2==0) {return;}
        //else 
        String[] copy=treeString.get(index1).clone();
        String s = copy[index2-1];
        copy[index2-1]=copy[index2];
        copy[index2]=s;
        treeString.set(index1,copy);
        //refresh the list
        initializeList2(index1);
        jList2.setSelectedIndex(index2-1);
    }//GEN-LAST:event_childUpActionPerformed

    private void childDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childDownActionPerformed
        // moving downstairs
        int index1 = jList1.getSelectedIndex();
        int index2 = jList2.getSelectedIndex();
        //if we are on the top of the list we do nothing
        if (index2==treeString.get(index1).length-1) {return;}
        //else 
        String[] copy=treeString.get(index1).clone();
        String s = copy[index2+1];
        copy[index2+1]=copy[index2];
        copy[index2]=s;
        treeString.set(index1,copy);
        //refresh the list
        initializeList2(index1);
        jList2.setSelectedIndex(index2+1);
    }//GEN-LAST:event_childDownActionPerformed

    private void removeParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeParentActionPerformed
        //remove a parent
        int n = JOptionPane.showConfirmDialog(this,"Are you sure you want to remove this category? This will also remove the children "
                + "of this category.", "Remove category", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.NO_OPTION) {
            //we do nothing if we don't want to remove
        } else {
            int index = jList1.getSelectedIndex();
            treeString.remove(index); //we remove the selected line
            initializeList1(); 
            String[] vide = { };
            jList1.clearSelection();
            jList2.setListData(vide);
        }
        
    }//GEN-LAST:event_removeParentActionPerformed

    private void removeChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeChildActionPerformed
        // We don't allow to remove the 'Other' subcategory
        if ("Other".equals(jList2.getSelectedValue())) {
            JOptionPane.showMessageDialog(this, "You are not allowed to remove this child",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int n = JOptionPane.showConfirmDialog(this,"Are you sure you want to remove this subcategory?", "Remove subcategory", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.NO_OPTION) {
            //we do nothing if we don't want to remove
        } else {
            int index1 = jList1.getSelectedIndex();
            int index2 = jList2.getSelectedIndex();
            String[] subCat = new String[treeString.get(index1).length-1];      //one string less 
            int j=0;
            for (int i=0; i<treeString.get(index1).length; i++) {
                if (i!=index2) {
                    subCat[j]=treeString.get(index1)[i];
                    j++;
                } 
            }
            treeString.set(index1,subCat);
            //refresh the list
            initializeList2(index1);
             
        }
    }//GEN-LAST:event_removeChildActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        // TODO manage the problems that can appear in the data base if categories were modified or removed
        ArrayList<Integer> pb = checkIntegrity();
        if (pb.get(0)!=0) {
            solveConflict(pb);
        }
        //here there is no more conflict
        //we can write the new categories in the file
        //and update the tree and table

        //register the change in the file
        String textBefore="";
        String textAfter="";
        Charset charset = Charset.forName("US-ASCII");
        Path file = FileSystems.getDefault().getPath("Try", "products.txt"); 
        try (BufferedReader reader = Files.newBufferedReader(file, charset)) {
            String line=reader.readLine();
            textBefore+=line+"\n";
            while (!line.equals("$tree$")) {
                line=reader.readLine();
                textBefore+=line+"\n";
            } 
            //we read the lines until the end of the tree
            line=reader.readLine();
            while (!line.equals("$endtree$")) {
                line=reader.readLine();
            } 
            //we stock the other lines of the files
            textAfter+=line+"\n";
            line=reader.readLine();
            textAfter+=line+"\n";
            while (line!=null) {
                line=reader.readLine();
                textAfter+=line+"\n";
            } 
            textAfter=textAfter.replace("null\n", "");
            
            //here we are in the right place in the file
            try (BufferedWriter writer = Files.newBufferedWriter(file, charset)) {
                String newText=textBefore;
                for (int i=0; i<treeString.size(); i++) {
                    String newline = String.join("/", treeString.get(i));
                    newText+=newline+"\n";
                }
                newText+=textAfter;
                writer.write(newText, 0, newText.length());
                writer.close();
            } catch (IOException x) {
                JOptionPane.showMessageDialog(this, "Problem saving the tree"+x.getMessage(),
                    "Warning", JOptionPane.ERROR_MESSAGE);
            }
            reader.close();
        } catch (IOException x) {
            JOptionPane.showMessageDialog(this, "Problem saving the tree"+x.getMessage(),
                    "Warning", JOptionPane.ERROR_MESSAGE);
        } 
        
        //update the table
        try {
            product.createNewTableModel();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Unexpected error, problem creating table\nDetails : "+ex.getMessage(),
                    "Warning", JOptionPane.ERROR_MESSAGE);
        }
        
        //update the tree
        product.updateTree(treeString);
        
        this.dispose();
        
    }//GEN-LAST:event_finishButtonActionPerformed

    
    private ArrayList<Integer> checkIntegrity() {
        //TODO check if there are problems in the data base category field
        //return the number of problems, 0 if no problem, -1 if we have an error with the request
        //build all the string we need to test
        ArrayList<String> cat = new ArrayList<>();
        for (int i=0; i<treeString.size(); i++) {
           for (int j=0; j<treeString.get(i).length-1; j++) {
                cat.add("'"+treeString.get(i)[0]+"/"+treeString.get(i)[j+1]+"'");
            }
        }
        //build the where request part
        String where="";
        for (int i=0; i<cat.size(); i++) {
            if (i!=cat.size()-1) {
                where+="category<>"+cat.get(i)+" AND ";
            } else {
                where+="category<>"+cat.get(i);
            }
        }

        ArrayList<Integer> result = new ArrayList<>();
        Statement stmt=null;
        try{
            stmt = product.getConnection().createStatement();
            String sqlQuery;
            sqlQuery="select count(*) from V_Products where "+where+" union "+"select pr_id from V_Products where "+where;
            ResultSet rs = stmt.executeQuery(sqlQuery);
            if (rs.next()) { 
                result.add(rs.getInt("count(*)"));
            } 
            while (rs.next()) {
                result.add(rs.getInt("count(*)"));
            }
            return result;
        } catch(SQLException se) {
            //Handle errors for JDBC
            JOptionPane.showMessageDialog(this, "Unexpected error, Request problem\nDetails : "+se.getMessage(),
                "Warning", JOptionPane.ERROR_MESSAGE);
            return null;
        } finally {
            //finally block used to close resources
            try{
                if(stmt!=null)
                 stmt.close();
            }catch(SQLException se2){  return null; }// nothing we can do
        }//end finally
        
    }
    
    private void solveConflict(ArrayList<Integer> pb) {
        //pb contains the number of problem in first position and the product id corresponding
        //for all the problem we resolve them creating a SolveCatConflict custom dialog 
        JFrame ancestor = (JFrame) SwingUtilities.getWindowAncestor(this);
        int [] p= new int[2];
        for (int i=0; i<pb.size()-1; i++) {
            p[0]=pb.get(0)-i;
            p[1]=pb.get(i+1);
            SolveCatConflict solve = new SolveCatConflict(ancestor,true,this,p);
            solve.setLocationRelativeTo(null);
            solve.setVisible(true);
        }
            
    }
    
    public ProductTab getProductTab() {
        return product;
    }
    
    public ArrayList<String[]> getTreeString() {
        return treeString;
    }
    

    private final ProductTab product;
    private ArrayList<String[]> treeString;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addChildButton;
    private javax.swing.JButton addParentButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton childDown;
    private javax.swing.JButton childUp;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton modifyChild;
    private javax.swing.JButton modifyParent;
    private javax.swing.JButton parentDown;
    private javax.swing.JButton parentUp;
    private javax.swing.JButton removeChild;
    private javax.swing.JButton removeParent;
    // End of variables declaration//GEN-END:variables
}
