import static java.awt.AWTEvent.ITEM_EVENT_MASK;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author brendan
 */
public class UpdateOrder extends javax.swing.JDialog {

    /**
     * Creates new form UpdateOrder
     */
    public UpdateOrder(java.awt.Frame parent, OrderTab orderT, Long ordId, boolean modal) {
        super(parent, modal);
        
        
        this.orderId = ordId;
        this.order = orderT;
        initComponents();
        initLab();
        initTable();
        initTotal();
        
        ListenItem.setActive(true);
        ListenChange.setActive(true);
        ListenDocument.setActive(true);
        
        jCheckBox1.addItemListener(new ListenItem() {
            @Override
            public void doPerformAction(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        
        jCheckBox2.addItemListener(new ListenItem() {
            @Override
            public void doPerformAction(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });
        
        jComboBox2.addItemListener(new ListenItem() {
            @Override
            public void doPerformAction(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        
        jComboBox3.addItemListener(new ListenItem() {
            @Override
            public void doPerformAction(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        
        jComboBox4.addItemListener(new ListenItem() {
            @Override
            public void doPerformAction(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        
        jComboBox5.addItemListener(new ListenItem() {
            @Override
            public void doPerformAction(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        
        jSpinner1.addChangeListener(new ListenChange() {
            @Override
            public void doPerformAction(ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        
        
        //Pour que le jspinner ne soit pas editable
        ((JSpinner.DefaultEditor) jSpinner1.getEditor()).getTextField().setEditable(false);
        
        //add listeners to the fields
        jTextField1.getDocument().addDocumentListener(new ListenDocument() {
            @Override
            public void doPerformAction(DocumentEvent evt) {
                jTextField1StateChanged(evt);
            }
        });
        
        jTextField2.getDocument().addDocumentListener(new ListenDocument() {
            @Override
            public void doPerformAction(DocumentEvent evt) {
                jTextField2StateChanged(evt);
            }
        });
        
        jTextField3.getDocument().addDocumentListener(new ListenDocument() {
            @Override
            public void doPerformAction(DocumentEvent evt) {
                jTextField3StateChanged(evt);
            }
        });
        
        jTextField4.getDocument().addDocumentListener(new ListenDocument() {
            @Override
            public void doPerformAction(DocumentEvent evt) {
                jTextField4StateChanged(evt);
            }
        });
        
        jTextArea2.getDocument().addDocumentListener(new ListenDocument() {
            @Override
            public void doPerformAction(DocumentEvent evt) {
                jTextArea2StateChanged(evt);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Finish");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Order number :");

        jLabel2.setText("jLabel2");

        jLabel3.setText("Date of order : ");

        jLabel4.setText("jLabel4");

        jLabel5.setText("Client : ");

        jLabel6.setText("jLabel6");

        jLabel7.setText("Status : ");

        jLabel9.setText("Sending cost : ");

        jLabel11.setText("RMB");

        jLabel12.setText("Order infos : ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel13.setText("Articles ordered");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Brand", "Name", "Status", "Paid", "Money received"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel15.setText("Quantity : ");
        jLabel15.setEnabled(false);

        jLabel16.setText("Selling price : ");
        jLabel16.setEnabled(false);

        jLabel18.setText("Order status : ");
        jLabel18.setEnabled(false);

        jLabel20.setText("Buying price : ");
        jLabel20.setEnabled(false);

        jLabel23.setText("Change rate (the date of purchase) :  1");
        jLabel23.setEnabled(false);

        jLabel24.setText("sellingUnit");
        jLabel24.setEnabled(false);

        jLabel25.setText("Remark about this article : ");
        jLabel25.setEnabled(false);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea2);

        jLabel26.setText("TOTAL : ");

        jLabel27.setText("Number of articles : ");

        jLabel28.setText("jLabel28");

        jLabel29.setText("Selling price : ");

        jLabel30.setText("jLabel30");

        jLabel31.setText("Buying price : ");

        jLabel32.setText("jLabel32");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not sent", "Sent to client", "Received by client" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));
        jSpinner1.setEnabled(false);

        jTextField1.setText(" - ");
        jTextField1.setEnabled(false);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RMB", "Euros" }));
        jComboBox2.setEnabled(false);

        jCheckBox1.setText("price yet to be fixed");
        jCheckBox1.setEnabled(false);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBox3.setEnabled(false);

        jTextField2.setText(" - ");
        jTextField2.setEnabled(false);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Euros", "RMB" }));
        jComboBox4.setEnabled(false);
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });

        jLabel33.setText("=");
        jLabel33.setEnabled(false);

        jTextField3.setText(" - ");
        jTextField3.setEnabled(false);

        jLabel34.setText("buyingUnit");
        jLabel34.setEnabled(false);

        jLabel35.setText("Order");

        jCheckBox2.setText("Paid");
        jCheckBox2.setEnabled(false);

        jLabel8.setText("-  Money received : ");
        jLabel8.setEnabled(false);

        jTextField4.setText(" - ");
        jTextField4.setEnabled(false);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RMB", "Euros" }));
        jComboBox5.setEnabled(false);

        jButton3.setText("Reset changes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Update table");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 746, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel2)
                                        .addGap(253, 253, 253)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel9))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel11))
                                                    .addComponent(jScrollPane1)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel29)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel30))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel27)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel28))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel31)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel32)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(3, 3, 3)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel24)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel33)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel34))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 52, Short.MAX_VALUE)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox2)
                            .addComponent(jLabel8)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel33)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        String orderState = (String) jComboBox1.getSelectedItem();
        if (("Sent to client".equals(orderState) || "Received by client".equals(orderState)) && " - ".equals(jTextField5.getText())) {
            String sendCost = JOptionPane.showInputDialog (this, "Sending cost (in RMB) :") ;
            
            if (sendCost==null) { return; }
            
            while (!Utilities.isDouble(sendCost,"The sending cost should be a number",this)) {
                sendCost = JOptionPane.showInputDialog (this, "Sending cost (in RMB) :") ;
                if (sendCost==null) { return; }
            } 
            jTextField5.setText(sendCost);
            jTextField5.setEnabled(true);
            jLabel11.setText("RMB");
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    
    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        int i = jTable1.getSelectedRow();
        
        ListenDocument.setActive(false);
        
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            jTextField1.setEnabled(false);
            jComboBox2.setEnabled(false);
            jTextField1.setText(" - ");
            jComboBox2.setSelectedItem("RMB");
            sellPrice.set(i, null);
            spUnit.set(i,null);
        } else {
            jTextField1.setEnabled(true);
            jTextField1.setText("");
            jComboBox2.setEnabled(true);
            spUnit.set(i, jComboBox2.getSelectedItem().toString());
        }
        
        ListenDocument.setActive(true);
    }
    
    
    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        int i = jTable1.getSelectedRow();
        
        ListenDocument.setActive(false);
        
        if (evt.getStateChange() != ItemEvent.SELECTED) {
            jTextField4.setEnabled(false);
            jComboBox5.setEnabled(false);
            jTextField4.setText(" - ");
            jComboBox5.setSelectedItem("RMB");
            paid.set(i, false);
            mrUnit.set(i,null);
            moneyReceived.set(i,null);
        } else {
            jTextField4.setEnabled(true);
            jTextField4.setText("");
            jComboBox5.setEnabled(true);
            paid.set(i, true);
            mrUnit.set(i,jComboBox5.getSelectedItem().toString()); 
        }
        
        ListenDocument.setActive(true);
    }
       
    
    
    
    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {          
        int i = jTable1.getSelectedRow();
        spUnit.set(i,jComboBox2.getSelectedItem().toString());
        
        jLabel24.setText(jComboBox2.getSelectedItem().toString());
        
        ListenDocument.setActive(false);
        
        if (jComboBox2.getSelectedItem() == jComboBox4.getSelectedItem()) {
            jTextField3.setText("1");
            rate.set(i,1.);
        } else {
            jTextField3.setText(" - ");
        }
        
        ListenDocument.setActive(true);
    }           
    
    
    
    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        int i = jTable1.getSelectedRow();
        
        switch (jComboBox3.getSelectedItem().toString()) {
            case "Not purchased" :
                articleState.set(i,0);
                bpUnit.set(i,null);
                buyPrice.set(i,null);
                rate.set(i,null);
                break;
            case "Purchased" :
                articleState.set(i,1);
                bpUnit.set(i,jComboBox4.getSelectedItem().toString());
                break;
            case "Sent to China" :
                articleState.set(i,2);
                bpUnit.set(i,jComboBox4.getSelectedItem().toString());
                break;
            case "Received in China" :
                articleState.set(i,3);
                bpUnit.set(i,jComboBox4.getSelectedItem().toString());
                break;
        }
        
        ListenDocument.setActive(false);
        
        String artState = jComboBox3.getSelectedItem().toString();
        if ("Not purchased".equals(artState)) {
            jTextField2.setEnabled(false);
            jTextField2.setText(" - ");
            jComboBox4.setEnabled(false);
            jComboBox4.setSelectedItem("Euros");
            jTextField3.setEnabled(false);
            jTextField3.setText(" - ");
        } else {
            jTextField2.setEnabled(true);
            jTextField2.setText(Double.toString(buyPrice.get(i)));
            jComboBox4.setEnabled(true);
            jComboBox4.setSelectedItem(bpUnit.get(i));
            jTextField3.setEnabled(true);
            jTextField3.setText(Double.toString(rate.get(i)));
        }
        
        ListenDocument.setActive(true);
        
    }
        
    
    
    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        int i = jTable1.getSelectedRow();
        bpUnit.set(i,jComboBox4.getSelectedItem().toString());
        
        jLabel34.setText(jComboBox4.getSelectedItem().toString());
        
        ListenDocument.setActive(false);
        
        if (jComboBox2.getSelectedItem() == jComboBox4.getSelectedItem()) {
            jTextField3.setText("1");
            rate.set(i,1.);
        } else {
            jTextField3.setText(" - ");
        }
        
        ListenDocument.setActive(true);
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    
    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {          
        int i = jTable1.getSelectedRow();
        mrUnit.set(i,jComboBox5.getSelectedItem().toString());
    }           
    
    private void jSpinner1StateChanged(ChangeEvent evt) {
        int i = jTable1.getSelectedRow();
        quantity.set(i, (int) jSpinner1.getValue());
    }
    
    
    //Undo the changes we eventually made in the dialog. Restore the data as they are in the db
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //TODO also for the status, sendCost and infos of the order
        ListenItem.setActive(false);
        ListenChange.setActive(false);
        ListenDocument.setActive(false);
        initLab();
        initTotal();
        initTable();
        ListenItem.setActive(true);
        ListenChange.setActive(true);
        ListenDocument.setActive(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    
    //when cliing the update table button
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ListenItem.setActive(false);
        ListenChange.setActive(false);
        ListenDocument.setActive(false);
        
        int nbRow=paid.size();
        
        Object data[][] = new Object [nbRow][5];
        
        //we need the brand and name of the products. they are in the first and second column of data 
        Statement stmt = null;
        int i=0;
        try{
            stmt = order.getMainWin().getConnection().createStatement();
            ResultSet rs = stmt.executeQuery("select prod.brand,prod.name "
                    + "from V_Ord_Articles as ordA inner join V_Products as prod on ordA.article=prod.pr_id "
                    + "where ordA.ord="+Long.toString(orderId));
            while (rs.next()) {
                data[i][0]=rs.getString("prod.brand");
                data[i][1]=rs.getString("prod.name");
                i++;
            }
        } catch(SQLException se) {
                //Handle errors for JDBC
                JOptionPane.showMessageDialog(this, "Unexpected error, select request problem\nDetails : "+se.getMessage(),
                    "Warning", JOptionPane.ERROR_MESSAGE);
        } finally {
            //finally block used to close resources
            try{
                if(stmt!=null)
                stmt.close();
            }catch(SQLException se2){ }// nothing we can do
        }//end finally
        
        
        //change the int code by the corresponding string (for the article state)
        //same for paid 0=No / 1=Yes
        for (i=0; i<nbRow; i++) {
            switch (articleState.get(i)) {
                case 0 : data[i][2]="Not purchased";
                    break;
                case 1 : data[i][2]="Purchased";
                    break;
                case 2 : data[i][2]="Sent to China";
                    break;    
                case 3 : data[i][2]="Received in China";
                    break;
            }
            
            if (paid.get(i) == false) {
                data[i][3]="No";
            } else {
                data[i][3]="Yes";
            }
            
            data[i][4]=moneyReceived.get(i);
        }
        
        String columnNames[] = new String[] { "Brand", "Name", "Status", "Paid", "Money received"} ;
        
        DefaultTableModel tableModel = new DefaultTableModel(data, columnNames) {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
      
        jTable1.setModel(tableModel);
          
        TableColumn col = jTable1.getColumnModel().getColumn(3);
        col.setPreferredWidth(25);
        
        updateTotal();
        
        ListenItem.setActive(true);
        ListenChange.setActive(true);
        ListenDocument.setActive(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    //when cliking the cancel button. Just close the window, without any change
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    //when cliking the finish button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO function to verify the dialog, not allow the price to be empty 
        //update of the orders table
        //we prepare the strings

        
        
        String status = jComboBox1.getSelectedItem().toString();
        String sendCost="";
        switch (status) {
            case "Not sent" :
                status = "0";
                sendCost="NULL";
                break;
            case "Sent to client" :
                status = "1";
                sendCost=jTextField5.getText();
                break;
            case "Received by client" :
                status = "2";
                sendCost=jTextField5.getText();
                break;
        }
        
        String infosOrd;
        if ("".equals(jTextArea1.getText())) {
            infosOrd= "'" + (jTextArea1.getText().replaceAll("'","\\\\'")) + "'";
        } else {
            infosOrd="NULL";
        }
        
        //we make the update statement
        Statement stmt = null;
        try{
            stmt = order.getMainWin().getConnection().createStatement();
            String sqlQuery;
            sqlQuery="UPDATE V_Orders SET state="+status+",send_cost="+sendCost+",infos="+infosOrd
                    + " where or_id="+Long.toString(orderId);
            int affectedRows = stmt.executeUpdate(sqlQuery); 
            //si 1 : normal, si 0 pas normal
            if (affectedRows == 0) {
                JOptionPane.showMessageDialog(this, "Request problem. No row inserted",
                  "Warning", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch(SQLException se) {
            //Handle errors for JDBC
            JOptionPane.showMessageDialog(this, "Unexpected error, Request problem\nDetails : "+se.getMessage(),
                "Warning", JOptionPane.ERROR_MESSAGE);
        } finally {
            //finally block used to close resources
            try{
                if(stmt!=null)
                stmt.close();
            }catch(SQLException se2){ }// nothing we can do
        }//end finally
        
        
        //next for the ord_articles table

        //we need the first oAr_id to start the update
        int id=0;
        stmt = null;
        try{
            stmt = order.getMainWin().getConnection().createStatement();
            String sqlQuery;
            sqlQuery="SELECT oAr_id from V_Ord_Articles where ord="+Long.toString(orderId);
            //we just want the first result
            ResultSet rs = stmt.executeQuery(sqlQuery);
            if (rs.next()) { 
                id = rs.getInt("oAr_id");
            }
            
        } catch(SQLException se) {
            //Handle errors for JDBC
            JOptionPane.showMessageDialog(this, "Unexpected error, Request problem\nDetails : "+se.getMessage(),
                "Warning", JOptionPane.ERROR_MESSAGE);
        } finally {
            //finally block used to close resources
            try{
                if(stmt!=null)
                stmt.close();
            }catch(SQLException se2){ }// nothing we can do
        }//end finally
        
        
        String paidStr,sellingPr,sellUnit,buyingPr,buyUnit,mr,moneyUnit,rateStr,artInfos;
        for (int i=0; i<quantity.size(); i++) {
            stmt = null;
            
            //prepare the strings
            if (sellPrice.get(i)!=0.0) {
                sellingPr=Double.toString(sellPrice.get(i));
                sellUnit = "'" + spUnit.get(i) + "'";
            } else {
                sellingPr="NULL";
                sellUnit = "NULL";
            }    
            
            if (buyPrice.get(i)!=0.0) {
                buyingPr=Double.toString(buyPrice.get(i));
                buyUnit = "'" + bpUnit.get(i) + "'";
            } else {
                buyingPr="NULL";
                buyUnit = "NULL";
            }   
            
            if (moneyReceived.get(i)!=0.0) {
                mr=Double.toString(moneyReceived.get(i));
                moneyUnit = "'" + mrUnit.get(i) + "'";
            } else {
                mr="NULL";
                moneyUnit = "NULL";
            } 
            
            if (rate.get(i)!=0.0) {
                rateStr=Double.toString(rate.get(i));
            } else {
                rateStr="NULL";
            }   
            
            if (infos.get(i)!=null) {
                artInfos="'" + (infos.get(i).replaceAll("'","\\\\'")) + "'";
            } else {
                artInfos = "NULL";
            }
            
            
            if (paid.get(i)) {
                paidStr = "1";
            } else {
                paidStr = "0";
            }
            try{
                stmt = order.getMainWin().getConnection().createStatement();
                String sqlQuery;
                sqlQuery="UPDATE V_Ord_Articles SET "
                        + "quantity="+quantity.get(i)
                        + ",selling_price="+sellingPr
                        + ",sp_unit="+sellUnit
                        + ",buying_price="+buyingPr
                        + ",bp_unit="+buyUnit
                        + ",change_rate="+rateStr
                        + ",paid="+paidStr
                        + ",state="+articleState.get(i) 
                        + ",infos="+artInfos
                        + ",money_received="+mr
                        + ",mr_unit="+moneyUnit
                        + " where oAr_id="+Integer.toString(id+i);
                
                int affectedRows = stmt.executeUpdate(sqlQuery); 
                //si 1 : normal, si 0 pas normal
                if (affectedRows == 0) {
                    JOptionPane.showMessageDialog(this, "Request problem. No row inserted",
                    "Warning", JOptionPane.ERROR_MESSAGE);
                }
            
            } catch(SQLException se) {
                //Handle errors for JDBC
                JOptionPane.showMessageDialog(this, "Unexpected error, Request problem\nDetails : "+se.getMessage(),
                    "Warning", JOptionPane.ERROR_MESSAGE);
            } finally {
                //finally block used to close resources
                try{
                    if(stmt!=null)
                    stmt.close();
                }catch(SQLException se2){ }// nothing we can do
            }//end finally
        }
        
        //update the orderTab
        try {
            order.updateOrderTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Unexpected error, problem updating the order table\nDetails : "+ex.getMessage(),
                  "Warning", JOptionPane.ERROR_MESSAGE);
        }
        
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jTextField1StateChanged(DocumentEvent e) {
        int i = jTable1.getSelectedRow();
        if (Utilities.isDouble(jTextField1)) {
            sellPrice.set(i,Double.parseDouble(jTextField1.getText())); 
        } else {
            sellPrice.set(i,null);
        }   
    }
    
    private void jTextField2StateChanged(DocumentEvent e) {
        int i = jTable1.getSelectedRow();
        if (Utilities.isDouble(jTextField2)) {
            buyPrice.set(i,Double.parseDouble(jTextField2.getText())); 
        } else {
            buyPrice.set(i,null);
        }
    }
    
    private void jTextField3StateChanged(DocumentEvent e) {
        int i = jTable1.getSelectedRow();
        if (Utilities.isDouble(jTextField3)) {
            rate.set(i,Double.parseDouble(jTextField3.getText())); 
        } else {
            rate.set(i,null);
        }
    }
    
    private void jTextField4StateChanged(DocumentEvent e) {
        int i = jTable1.getSelectedRow();
        if (Utilities.isDouble(jTextField4)) {
            moneyReceived.set(i,Double.parseDouble(jTextField4.getText())); 
        } else {
            moneyReceived.set(i,null); 
        }
    }
    
    private void jTextArea2StateChanged(DocumentEvent e) {
        int i = jTable1.getSelectedRow();
        infos.set(i,jTextArea2.getText()); 
    }
    
    private void initLab() { 

        String date = "";
        String clientName = "";
        String state="";
        String sendCost = "";
        String infos = "";
        String row = Long.toString(orderId);
        
        Statement stmt = null;
        try{
            stmt = order.getMainWin().getConnection().createStatement();
            String sqlQuery;
            sqlQuery="SELECT date,cl.name,state,send_cost,ord.infos from V_Orders as ord inner join V_Clients as cl on ord.clients=cl.cl_id "
                    + " where ord.or_id="+row;
            ResultSet rs = stmt.executeQuery(sqlQuery);
            if (rs.next()) { 
                date = rs.getString("date");
                clientName = rs.getString("cl.name");
                state = rs.getString("state");
                sendCost = rs.getString("send_cost");
                infos = rs.getString("infos");
            }
        } catch(SQLException se) {
            //Handle errors for JDBC
            JOptionPane.showMessageDialog(this, "Unexpected error, Request problem\nDetails : "+se.getMessage(),
                "Warning", JOptionPane.ERROR_MESSAGE);
        } finally {
            //finally block used to close resources
            try{
                if(stmt!=null)
                stmt.close();
            }catch(SQLException se2){ }// nothing we can do
        }//end finally
        
        
        jLabel2.setText(row);
        jLabel4.setText(date);
        jLabel6.setText(clientName);
        
        if ("0".equals(state)) {
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not sent", "Sent to client", "Received by client" }));
            jTextField5.setText(" - ");
            jTextField5.setEnabled(false);
            jLabel11.setText("");
        }
        if ("1".equals(state)) {
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sent to client", "Received by client" }));
            jTextField5.setText(sendCost);
            jTextField5.setEnabled(true);
            jLabel11.setText("RMB");
        }
        if ("2".equals(state)) {
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Received by client" }));
            jTextField5.setText(sendCost);
            jTextField5.setEnabled(true);
            jLabel11.setText("RMB");
        }

        jTextArea1.setText(infos);
    }
    
    private void initTable() {
        paid = new ArrayList<> ();
        moneyReceived = new ArrayList<> ();
        mrUnit = new ArrayList<> ();
        articleState = new ArrayList<> ();
        rate = new ArrayList<> ();
        infos = new ArrayList<> ();
        
        //initialisation of the different data fields 
        Statement stmt = null;
        try{
            stmt = order.getMainWin().getConnection().createStatement();
            ResultSet rs = stmt.executeQuery("select state,paid,money_received,mr_unit,change_rate,infos "
                    + "from V_Ord_Articles where ord="+Long.toString(orderId));
            while (rs.next()) {
                if (rs.getInt("paid") == 0) {
                    paid.add(false);
                } else {
                    paid.add(true);
                }
                moneyReceived.add(rs.getDouble("money_received"));
                mrUnit.add(rs.getString("mr_unit"));
                articleState.add(rs.getInt("state"));
                rate.add(rs.getDouble("change_rate"));
                infos.add(rs.getString("infos"));
            }
        } catch(SQLException se) {
                //Handle errors for JDBC
                JOptionPane.showMessageDialog(this, "Unexpected error, select request problem\nDetails : "+se.getMessage(),
                    "Warning", JOptionPane.ERROR_MESSAGE);
        } finally {
            //finally block used to close resources
            try{
                if(stmt!=null)
                stmt.close();
            }catch(SQLException se2){ }// nothing we can do
        }//end finally
        
        
        //Creation of the table
        stmt = null;
        try{
            stmt = order.getMainWin().getConnection().createStatement();
            ResultSet rs = stmt.executeQuery("select prod.brand as Brand,prod.name as Name,"
                    + "ord.state as Article_status,ord.paid as Paid,ord.money_received as Money_received from V_Ord_Articles AS ord inner join V_Products AS prod "
                    + "on ord.article=prod.pr_id inner join V_Orders on V_Orders.or_id=ord.ord where V_Orders.or_id="+Long.toString(orderId));
            jTable1.setModel(OrderTab.buildTableModel(rs));
        } catch(SQLException se) {
                //Handle errors for JDBC
                JOptionPane.showMessageDialog(this, "Unexpected error, select request problem\nDetails : "+se.getMessage(),
                    "Warning", JOptionPane.ERROR_MESSAGE);
        } finally {
            //finally block used to close resources
            try{
                if(stmt!=null)
                stmt.close();
            }catch(SQLException se2){ }// nothing we can do
        }//end finally
        

        int nbRow=paid.size();
        
        //change the int code by the corresponding string (for the article state)
        //same for paid 0=No / 1=Yes
        for (int i=0; i<nbRow; i++) {
            switch (jTable1.getValueAt(i,2).toString()) {
                case "0" : jTable1.setValueAt("Not purchased",i,2);
                    break;
                case "1" : jTable1.setValueAt("Purchased",i,2);
                    break;
                case "2" : jTable1.setValueAt("Sent to China",i,2);
                    break;    
                case "3" : jTable1.setValueAt("Received in China",i,2);
                    break;
            }
            switch (jTable1.getValueAt(i,3).toString()) {
                case "0" : jTable1.setValueAt("No",i,3);
                    break;
                case "1" : jTable1.setValueAt("Yes",i,3);
                    break;
            }
        }
        
        //change the width of the fourth column of the table
        TableColumn col = jTable1.getColumnModel().getColumn(3);
        col.setPreferredWidth(25);
        
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);  
        
        ListSelectionModel rowSM = jTable1.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                tableValueChangedEvent(e);  
            }
        });
        
        
    }
    
    private void initTotal() {
        quantity = new ArrayList<> ();
        sellPrice = new ArrayList<> ();
        spUnit = new ArrayList<> ();
        buyPrice = new ArrayList<> ();
        bpUnit = new ArrayList<> ();
        String incomplS = "";
        String incomplB = "";
        
        Statement stmt = null;
        try{
            stmt = order.getMainWin().getConnection().createStatement();
            ResultSet rs = stmt.executeQuery("select quantity,selling_price,sp_unit,buying_price,bp_unit "
                    + "from V_Ord_Articles where V_Ord_Articles.ord="+Long.toString(orderId));
            while (rs.next()) {
                quantity.add(rs.getInt("quantity"));
                sellPrice.add(rs.getDouble("selling_price"));
                spUnit.add(rs.getString("sp_unit"));
                buyPrice.add(rs.getDouble("buying_price"));
                bpUnit.add(rs.getString("bp_unit"));
            }
        } catch(SQLException se) {
                //Handle errors for JDBC
                JOptionPane.showMessageDialog(this, "Unexpected error, select request problem\nDetails : "+se.getMessage(),
                    "Warning", JOptionPane.ERROR_MESSAGE);
        } finally {
            //finally block used to close resources
            try{
                if(stmt!=null)
                stmt.close();
            }catch(SQLException se2){ }// nothing we can do
        }//end finally
        
        Double totRMB=0.;    
        Double totRMBbuy=0.; 
        Double totEur=0.;
        Double totEurbuy=0.;
        int totQuant = 0;
        for (int i=0; i<quantity.size(); i++) {        
            //for quantity
            totQuant += quantity.get(i);
            
            //for selling price
            if (null==spUnit.get(i)) {
                incomplS = " (incomplete information)";
            } else {
                switch (spUnit.get(i)) {
                    case "RMB":
                        totRMB += sellPrice.get(i) * quantity.get(i);
                        break;
                    case "Euros":
                        totEur += sellPrice.get(i) * quantity.get(i);
                        break;
                }
            }
            
            
            //for buying price
            if (null==bpUnit.get(i)) {
                incomplB = " (incomplete information)";
            } else {
                switch (bpUnit.get(i)) {
                    case "RMB":
                        totRMBbuy += buyPrice.get(i) * quantity.get(i);
                        break;
                    case "Euros":
                        totEurbuy += buyPrice.get(i) * quantity.get(i);
                        break;
                }
            }
 
        }
        
        String str="";
        if (totRMB!=0 && totEur!=0) {
            str = totRMB + " RMB + " + totEur + " Euros " + incomplS;
        }
        if (totRMB==0 && totEur!=0) {
            str = totEur + " Euros " + incomplS;
        }
        if (totRMB!=0 && totEur==0) {
            str = totRMB + " RMB " + incomplS;
        }
        if (totRMB==0 && totEur==0) {
            str = incomplS;
        }
        
        jLabel30.setText(str);
        jLabel28.setText(Integer.toString(totQuant));
        
        str="";
        if (totRMBbuy!=0 && totEurbuy!=0) {
            str = totRMBbuy + " RMB + " + totEurbuy + " Euros " + incomplB;
        }
        if (totRMBbuy==0 && totEurbuy!=0) {
            str = totEurbuy + " Euros " + incomplB;
        }
        if (totRMBbuy!=0 && totEurbuy==0) {
            str = totRMBbuy + " RMB " + incomplB;
        }
        if (totRMBbuy==0 && totEurbuy==0) {
            str = incomplB;
        }
        
        jLabel32.setText(str);
        
    }
    
    private void updateTotal() {
        String incomplS = "";
        String incomplB = "";
        Double totRMB=0.;    
        Double totRMBbuy=0.; 
        Double totEur=0.;
        Double totEurbuy=0.;
        int totQuant = 0;
        for (int i=0; i<quantity.size(); i++) {        
            //for quantity
            totQuant += quantity.get(i);
            
            //for selling price
            if (null==spUnit.get(i)) {
                incomplS = " (incomplete information)";
            } else {
                switch (spUnit.get(i)) {
                    case "RMB":
                        totRMB += sellPrice.get(i) * quantity.get(i);
                        break;
                    case "Euros":
                        totEur += sellPrice.get(i) * quantity.get(i);
                        break;
                }
            }
            
            
            //for buying price
            if (null==bpUnit.get(i)) {
                incomplB = " (incomplete information)";
            } else {
                switch (bpUnit.get(i)) {
                    case "RMB":
                        totRMBbuy += buyPrice.get(i) * quantity.get(i);
                        break;
                    case "Euros":
                        totEurbuy += buyPrice.get(i) * quantity.get(i);
                        break;
                }
            }
 
        }
        
        String str="";
        if (totRMB!=0 && totEur!=0) {
            str = totRMB + " RMB + " + totEur + " Euros " + incomplS;
        }
        if (totRMB==0 && totEur!=0) {
            str = totEur + " Euros " + incomplS;
        }
        if (totRMB!=0 && totEur==0) {
            str = totRMB + " RMB " + incomplS;
        }
        if (totRMB==0 && totEur==0) {
            str = incomplS;
        }
        
        jLabel30.setText(str);
        jLabel28.setText(Integer.toString(totQuant));
        
        str="";
        if (totRMBbuy!=0 && totEurbuy!=0) {
            str = totRMBbuy + " RMB + " + totEurbuy + " Euros " + incomplB;
        }
        if (totRMBbuy==0 && totEurbuy!=0) {
            str = totEurbuy + " Euros " + incomplB;
        }
        if (totRMBbuy!=0 && totEurbuy==0) {
            str = totRMBbuy + " RMB " + incomplB;
        }
        if (totRMBbuy==0 && totEurbuy==0) {
            str = incomplB;
        }
        
        jLabel32.setText(str);
    }
    
    
    private void tableValueChangedEvent(ListSelectionEvent e) {
        ListSelectionModel lsm = (ListSelectionModel)e.getSource();
        if (lsm.isSelectionEmpty()) {
            jLabel15.setEnabled(false);
            jSpinner1.setEnabled(false);
            jSpinner1.setValue(1);
            jLabel16.setEnabled(false);
            jTextField1.setEnabled(false);
            jTextField1.setText(" - ");
            jComboBox2.setEnabled(false);
            jCheckBox1.setEnabled(false);
            jCheckBox1.setSelected(false);
            jCheckBox2.setEnabled(false);
            jCheckBox2.setSelected(false);
            jLabel8.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField4.setText(" - ");
            jComboBox5.setEnabled(false);
            jLabel18.setEnabled(false);
            jComboBox3.setEnabled(false);
            jComboBox3.setModel(new DefaultComboBoxModel(new String[] { " - " } ));
            jLabel20.setEnabled(false);
            jTextField2.setEnabled(false);
            jTextField2.setText(" - ");
            jComboBox4.setEnabled(false);
            jLabel23.setEnabled(false);
            jLabel24.setEnabled(false);
            jLabel24.setText( "sellingUnit" );
            jLabel33.setEnabled(false);
            jTextField3.setEnabled(false);
            jTextField3.setText( " - " );
            jLabel34.setEnabled(false);
            jLabel34.setText( "sellingUnit" );
            jLabel25.setEnabled(false);
            jTextArea2.setEnabled(false);
            jTextArea2.setText("");
        } else {
            
            ListenItem.setActive(false);
            ListenChange.setActive(false);
            ListenDocument.setActive(false);
            
            int i = jTable1.getSelectedRow();

            jLabel15.setEnabled(true);
            jSpinner1.setEnabled(true);
            jSpinner1.setValue(quantity.get(i));
                    
            jLabel16.setEnabled(true);
            jCheckBox1.setEnabled(true);
            
            if (null==spUnit.get(i)) {
                jTextField1.setText(" - ");
                jTextField1.setEnabled(false);
                jComboBox2.setSelectedItem("RMB");
                jComboBox2.setEnabled(false);
                jCheckBox1.setSelected(true);
            } else {
                if (sellPrice.get(i)==0.0) {
                    jTextField1.setText("");
                } else {
                    jTextField1.setText(Double.toString(sellPrice.get(i)));
                }
                jTextField1.setEnabled(true);
                jCheckBox1.setSelected(false);
                jComboBox2.setSelectedItem(spUnit.get(i));
                jComboBox2.setEnabled(true);
            }
                    
            jCheckBox2.setEnabled(true);
            jLabel8.setEnabled(true);
            if (!paid.get(i)) {
                jCheckBox2.setSelected(false);
                jTextField4.setText(" - ");
                jTextField4.setEnabled(false);
                jComboBox5.setSelectedItem("RMB");
                jComboBox5.setEnabled(false);
            } else {
                jCheckBox2.setSelected(true);
                if (moneyReceived.get(i)==0.0) {
                    jTextField4.setText("");
                } else {
                    jTextField4.setText(Double.toString(moneyReceived.get(i)));
                }
                
                jTextField4.setEnabled(true);
                jComboBox5.setSelectedItem(mrUnit.get(i));
                jComboBox5.setEnabled(true);
            }
                    
            jLabel18.setEnabled(true);
            jLabel20.setEnabled(true);
            jLabel23.setEnabled(true);
            jLabel24.setEnabled(true);
            jLabel24.setText(jComboBox2.getSelectedItem().toString());
            jLabel33.setEnabled(true);
            jLabel34.setEnabled(true);
            jLabel34.setText(jComboBox4.getSelectedItem().toString());
            jComboBox3.setEnabled(true);
            switch (articleState.get(i)) {
                case 0 :
                    jComboBox3.setModel(new DefaultComboBoxModel(new String[] { "Not purchased","Purchased","Sent to China","Received in China"}));
                    jTextField2.setEnabled(false);
                    jTextField2.setText(" - ");
                    jComboBox4.setEnabled(false);
                    jComboBox4.setSelectedItem("Euros");
                    jTextField3.setEnabled(false);
                    jTextField3.setText( " - " );
                    break;
                case 1 :
                    jComboBox3.setModel(new DefaultComboBoxModel(new String[] { "Purchased","Sent to China","Received in China"}));
                    jTextField2.setEnabled(true);
                    if (buyPrice.get(i)==0.0) {
                        jTextField2.setText("");
                    } else {
                        jTextField2.setText(Double.toString(buyPrice.get(i)));
                    }
                    jComboBox4.setEnabled(true);
                    jComboBox4.setSelectedItem(bpUnit.get(i));
                    jTextField3.setEnabled(true);
                    if (rate.get(i)==0.0) {
                        jTextField3.setText("");
                    } else {
                        jTextField3.setText(Double.toString(rate.get(i)));
                    }
                    break;
                case 2 :
                    jComboBox3.setModel(new DefaultComboBoxModel(new String[]{"Sent to China", "Received in China"}));
                    jTextField2.setEnabled(true);
                    if (buyPrice.get(i)==0.0) {
                        jTextField2.setText("");
                    } else {
                        jTextField2.setText(Double.toString(buyPrice.get(i)));
                    }
                    jComboBox4.setEnabled(true);
                    jComboBox4.setSelectedItem(bpUnit.get(i));
                    jTextField3.setEnabled(true);
                    if (rate.get(i)==0.0) {
                        jTextField3.setText("");
                    } else {
                        jTextField3.setText(Double.toString(rate.get(i)));
                    }
                    break;
                case 3 :
                    jComboBox3.setModel(new DefaultComboBoxModel(new String[]{"Received in China"}));
                    jTextField2.setEnabled(true);
                    if (buyPrice.get(i)==0.0) {
                        jTextField2.setText("");
                    } else {
                        jTextField2.setText(Double.toString(buyPrice.get(i)));
                    }
                    jComboBox4.setEnabled(true);
                    jComboBox4.setSelectedItem(bpUnit.get(i));
                    jTextField3.setEnabled(true);
                    if (rate.get(i)==0.0) {
                        jTextField3.setText("");
                    } else {
                        jTextField3.setText(Double.toString(rate.get(i)));
                    }
                    break;
            }
                    
            jLabel25.setEnabled(true);
            jTextArea2.setEnabled(true);
            jTextArea2.setText(infos.get(i));
            
            ListenItem.setActive(true);
            ListenChange.setActive(true);
            ListenDocument.setActive(true);
   
        }
    }
    
    
    private final Long orderId;
    private final OrderTab order;
    
    //the articles infos we are going to modify 
    private ArrayList<Integer> quantity;
    private ArrayList<Double> sellPrice;
    private ArrayList<String> spUnit;
    private ArrayList<Double> buyPrice;
    private ArrayList<String> bpUnit;
    private ArrayList<Boolean> paid;
    private ArrayList<Double> moneyReceived;
    private ArrayList<String> mrUnit;
    private ArrayList<Integer> articleState;
    private ArrayList<Double> rate;
    private ArrayList<String> infos;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    
}

abstract class ListenItem implements ItemListener { 
    
    private static boolean active = true;
    
    public static void setActive(boolean active){
        ListenItem.active = active;
    }
    
    protected abstract void doPerformAction(ItemEvent e);
    
    @Override
    public void itemStateChanged(ItemEvent e) {
        if(active){
            doPerformAction(e);
        }
    }
}


abstract class ListenChange implements ChangeListener { 
    
    private static boolean active = true;
    
    public static void setActive(boolean active){
        ListenChange.active = active;
    }
    
    protected abstract void doPerformAction(ChangeEvent e);
    
    @Override
    public void stateChanged(ChangeEvent e) {
        if(active){
            doPerformAction(e);
        }
    }
}


abstract class ListenDocument implements DocumentListener {
    
    private static boolean active = true;
    
    public static void setActive(boolean active){
        ListenDocument.active = active;
    }
    
    protected abstract void doPerformAction(DocumentEvent e);
    
    @Override
    public void insertUpdate(DocumentEvent e) {
        if (active) {
            doPerformAction(e);
        }
    }
    
    @Override
    public void removeUpdate(DocumentEvent e) {
        if (active) {
            doPerformAction(e);
        }
    }
        
    @Override
    public void changedUpdate(DocumentEvent e) {
        if (active) {
            doPerformAction(e);
        }
    }
    
}